# Generated by Django 5.0 on 2023-12-19 09:06

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=50)),
                ('file_type', models.CharField(max_length=50)),
                ('file_path', models.FileField(upload_to=book.models.get_file_path)),
                ('file_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_image_path', models.ImageField(upload_to=book.models.get_cover_image_path)),
            ],
        ),
    ]
