# Generated by Django 5.0 on 2023-12-13 07:33

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=book.models.get_file_path),
        ),
        migrations.AddField(
            model_name='book',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to=book.models.get_file_path),
        ),
    ]
