# Generated by Django 5.0 on 2023-12-14 06:19

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_remove_book_cover_remove_book_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_path',
            field=models.ImageField(blank=True, null=True, upload_to=book.models.get_cover_image_path),
        ),
    ]
