# Generated by Django 5.0 on 2023-12-15 08:55

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_file_size_alter_book_cover_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image_path',
            field=models.ImageField(upload_to=book.models.get_cover_image_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_path',
            field=models.FileField(upload_to=book.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='file_size',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
